### ISSUE TITLE
Release 0.3.0 is buggy

### ISSUE THREAD

**Issue by 28140** [dduong42/s3manifestcollectstatic#3]
Hi there!

Your package doesn’t (seem to) work when the custom storage backend for Django is set to DigitalOcean's Spaces (S3 compatible service).

In your package description, you say that “… When used with storages.backends.s3boto3.S3ManifestStaticStorage, collectstatic uploads the files twice…”.

I’m not using storages.backends.s3boto3.S3ManifestStaticStorage directly, instead I use the following:

```
STORAGES = {
    "default": {
        "BACKEND": “company.utils.storages.MediaRootS3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": “company.utils.storages.StaticRootS3Boto3Storage",
    },
}
```

And here’s my “company.utils.storages.py”:

```
from storages.backends.s3boto3 import S3ManifestStaticStorage, S3Boto3Storage


class MediaRootS3Boto3Storage(S3Boto3Storage):
    bucket_name = "company"
    location = "media"
    default_acl = "public-read"
    file_overwrite = True
    custom_domain = “company.fra1.cdn.digitaloceanspaces.com"


class StaticRootS3Boto3Storage(S3ManifestStaticStorage):
    bucket_name = "company"
    location = "static"
    default_acl = "public-read"
    file_overwrite = True
    custom_domain = “company.fra1.cdn.digitaloceanspaces.com"
```

In your present release, “staticfiles_storage” has the type “django.contrib.staticfiles.storage.ConfiguredStorage”.
I don’t think that’s correct.
I think its type should be the class from “settings.STORAGES['staticfiles']['BACKEND’]”...

Here’s my proposed solution, which works for DigitalOcean, and I guess for other providers also:

```
@@ -6,13 +6,17 @@ from tempfile import TemporaryDirectory
 
 from django import VERSION
 from django.conf import settings
-from django.contrib.staticfiles.storage import staticfiles_storage
 from django.core.management import call_command
 from django.core.management.base import BaseCommand, CommandError
+from django.utils.module_loading import import_string
 
 
 MANIFEST_PATH = "staticfiles.json"
 
+staticfiles_storage_class = settings.STATICFILES_STORAGE if VERSION < (4, 2) or settings.is_overridden("STATICFILES_STORAGE") else settings.STORAGES['staticfiles']['BACKEND']
+staticfiles_storage = import_string(staticfiles_storage_class)()
+
+
 class Command(BaseCommand):
     def log(self, msg, level=2):
         """
```

You'll figure out the rest.

Looking forward to your reply.

Thanks!

PS:

I’m using Python 3.11.4, Django 4.2.2, and django-storages 1.13.2

PPS:

Or am I doing it wrong?

**Comment by dduong42** [comment]
Can you show me what doesn't work? `django.contrib.staticfiles.storage.ConfiguredStorage` is a wrapper around the actual storage backend.

**Comment by 28140** [comment]
If you want to simply add 2 print statement:

```
def _save_asset(path):
    path_obj = Path(tmpdirname) / path
    with path_obj.open("rb") as f:

        print(type(staticfiles_storage))
        print(staticfiles_storage)

        staticfiles_storage.save(path, f)
    return path
```

You will get this:

```
<class 'django.contrib.staticfiles.storage.ConfiguredStorage'>
<django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x104e2f2d0>
```

Now the source code for the ManifestStaticFilesStorage class:

```
class ManifestStaticFilesStorage(ManifestFilesMixin, StaticFilesStorage):
    """
    A static file system storage backend which also saves
    hashed copies of the files it saves.
    """

    pass
```

A static **file system** storage backend (emphasis mine)...

Furthermore, if you load the code in an IDE (like PyCharm, for example), you will see with the help of AutoComplete that the class `staticfiles_storage` doesn't even have a `save` method...

You will find a not-so-elegant solution in my original comment.

If you can think of something more Pythonic, go ahead, be my guest!

Thanks and looking forward to your reply!

**Comment by 28140** [comment]
> Can you show me what doesn't work? `django.contrib.staticfiles.storage.ConfiguredStorage` is a wrapper around the actual storage backend.

In **my** case, the actual uploading of files.

The `staticfiles_storage.save(path, f)` step.

I ran `python manage.py s3manifestcollectstatic -f -w 1 -v 2 --settings=config.settings.local` and while the files **are** reported as uploaded, they are not [uploaded].

And the whole thing finishes in like 5 seconds, with the `-w 1` option, for ~2,000 static files...

It doesn't upload anything, of course, I checked.

The network monitor stays flat, no Internet traffic.

As opposed to my proposed "solution"...

Once again, thank you for your time, and looking forward to your reply!

**Comment by dduong42** [comment]
> ```
> <class 'django.contrib.staticfiles.storage.ConfiguredStorage'>
> <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x104e2f2d0>
> ```

This is normal, that's because the backend in wrapped in that object.

By modifying a little bit `StaticRootS3Boto3Storage`, so that it's a plain object
```python
class StaticRootS3Boto3Storage:
    something = "test"
```

You will find this:
```
>>> from django.contrib.staticfiles.storage import staticfiles_storage
>>> type(staticfiles_storage)
<class 'django.contrib.staticfiles.storage.ConfiguredStorage'>
>>> staticfiles_storage.something
'test'
```

> In **my** case, the actual uploading of files.
> 
> The `staticfiles_storage.save(path, f)` step.
> 
> I ran `python manage.py s3manifestcollectstatic -f -w 1 -v 2 --settings=config.settings.local` and while the files **are** reported as uploaded, they are not [uploaded].
> 
> And the whole thing finishes in like 5 seconds, with the `-w 1` option, for ~2,000 static files...
> 
> It doesn't upload anything, of course, I checked.
> 
> The network monitor stays flat, no Internet traffic.
> 
> As opposed to my proposed "solution"...
> 
> Once again, thank you for your time, and looking forward to your reply!

I'll try to reproduce that and see.

**Comment by dduong42** [comment]
@28140  Should be fixed. Tell me if it worked.

**Comment by 28140** [comment]
Perfectly!

:-)

Thank you very much!
